steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - partialupdate_terraform
      - --runtime=go121
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=PartialUpdateEmployee
      - --region=us-central1
      - --project=takeoff-task-3
